# Choose an agent virtual image
pool:
  vmImage: ubuntu-16.04
container:
  image: eschnett/mpi-hs

steps:
- script: |
    set -euxo pipefail
    git clone https://github.com/eschnett/mpi-hs-store.git
  displayName: Download package
- script: |
    set -euxo pipefail
    cd mpi-hs-store
    stack build --flag mpi-hs:mpich-ubuntu --test --no-run-tests --haddock --no-haddock-deps
  displayName: Build package
- script: |
    set -euxo pipefail
    cd mpi-hs-store
    mpiexec stack exec version
    mpiexec -n 3 stack exec example1
    mpiexec -n 3 stack exec example2
  displayName: Run examples
- script: |
    set -euxo pipefail
    cd mpi-hs-store
    mpiexec -n 3 stack exec -- $(stack path --dist-dir)/build/mpi-test-store/mpi-test-store
  displayName: Run tests
